### ISSUE TITLE
PyPi Package Versions

### ISSUE THREAD

**Issue by Eric-Vin** [meelgroup/approxmc#32]
Thanks so much for posting the new ApproxMC release on PyPi! Unfortunately it looks like there's only a single wheel, which is for Python 3.7 on Linux (https://pypi.org/project/pyapproxmc/4.1.9/#files), which is somewhat restrictive. Would it be possible to post the source archive like what was done in the previous version (https://pypi.org/project/pyapproxmc/4.1.8/#files) so that it can be built for arbitrary Python versions and operating systems?

**Comment by msoos** [comment]
Hi Eric,

Thanks, that's a good catch actually! I have fixed it so now have all python packages from 3.7 all the way to 3.11. Note that previously it was a source package, which is now not built unfortunately. Let me know if that's an issue. However, this fix should close this issue since the issue was about versions, and we now have every meaningful Python version built as a wheel. I am adding this fix to UniGen and CMS as well, soon they will have all these versions too :)

Thanks again for spotting this! I hope this fixes the issue! Cheers,

Mate

**Comment by Eric-Vin** [comment]
Hi Mate,

Thanks so much for adding the additional Python versions! Unfortunately I think people on non-Linux/x86_64 operating systems will still be unable to use the package, as the wheels are only for Linux/x86_64 systems. Would it be possible to also add the source package to PyPi so everyone can build from source as a backup? It believe you can have both the source archive and the wheels on PyPi, and the wheels are used by default when compatible. I think the source archive should be build by default alongside any wheels, according to this page (https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives), so hopefully that can be integrated into the deployment script.

Thanks so much for your help!
- Eric

**Comment by msoos** [comment]
Thanks for pointing this out! I spent about two evenings on that build system, already -- it was fun work but I'm a bit exhausted :( Perhaps you could take a peek and see how it could be fixed to also include a source archive upload? Otherwise, I'll look at it in a few days,

Mate

**Comment by msoos** [comment]
OK, I fixed it up for all 3, source package is up up for approxmc, and unigen & CMS will now follow. I hope this fixes the issue,

Mate

**Comment by Eric-Vin** [comment]
Hi Mate,

Thanks so much for fixing it so quickly! I just checked and it's working perfectly now.

Thanks again!
Eric
