### ISSUE TITLE
pyapproxmc: setting the memory/time limit

### ISSUE THREAD

**Issue by yizza91** [meelgroup/approxmc#35]
Can we fix the memory and time limit of the Counter using the python interface?

**Comment by msoos** [comment]
Hi,

Currently, unfortunately, this is not supported. Would this be useful for your use-case? Is there a particular use-case you are looking for?

Thanks,

Mate

**Comment by yizza91** [comment]
My program instruments a linear number of call to approxmc (on the same cnf formula + assumptions, so different sub-formulas) and I want to fix a time/memory limit for each call, as some calls consume too much resources. 
Therefore, in case of an expensive call,  the procedure should skip it.

Yacine

**Comment by msoos** [comment]
Hi,

Let's talk about this once I'm back in Singapore, in about a week. It's just a lot of work and I'm not 10% sure it's needed. Let's discuss in-person and then we can see if it's indeed needed.

Cheers,

Mate

**Comment by yizza91** [comment]
The issue is that when I run approxmc with python interface it stops the process (killed -9) however the binary file (c++ compiled) returns a results

**Comment by msoos** [comment]
Hi,

Oh, that's a bug actually. Can you please send me how to reproduce?

Thanks,

Mate

**Comment by yizza91** [comment]
Okay, I sent you an email. 

Yacine

**Comment by yizza91** [comment]
I use the param projection when calling the function count() and I get an error. Have you tried to replicate with the formula that I've sent? and do you get an error *killed -9* or it returns the solution?

**Comment by msoos** [comment]
It returns the solution quickly. You are likely using it wrong. Please:

   1. "sudo pip uninstall pyapproxmc"
   2. "pip uninstall pyapproxmc"
   3. "pip install pyapproxmc"
   4. "python test.py german-0.cnf"

This will produce:

$ python test.py ../../build/yacine/german/german-0.cnf
using file:  ../../build/yacine/german/german-0.cnf
num cls:  19932
projection:  [1087, 1079, 1078, 1075, 4181, 4182, 4183, 4184, 4185, 4186,
1099, 1069, 1127, 1115, 1100, 11
08, 1128, 1126, 1088, 1105, 1121, 1095, 1104, 1139, 1076, 1096, 1097, 1082,
1086, 1109, 1117, 1103, 4199,
4200, 4201, 1092, 1083, 1122, 1060, 1062, 1063, 1065]
c WARNING: Turning off gates, because the sampling size is small, so we can
just do it
c [arjun-simp] equiv-subform removed: 0 perc: 0.00 total equiv_subform now:
0 T: 0.07
c [arjun-simp] CMS::simplify() with no BVE, intree probe...
c [arjun-simp] CMS::simplify() with no BVE finished. T: 0.41
c [arjun-simp] Removed eq lits: 0 new size: 42
c [arjun-simp] Removed set       : 0 new size: 42
c [arjun-simp] Removed set       : 0 new size: 42
c [arjun-simp] Removed eq lits: 2 new size: 40
c [arjun-simp] probe removed: 2 perc: 4.76 T: 0.46
c [arjun-simp] equiv-subform removed: 0 perc: 0.00 total equiv_subform now:
0 T: 0.07
c [arjun] simplification finished  removed: 2 perc: 4.76 T: 4.65
c [arjun] Duplicating CNF...
c [arjun] Duplicated CNF. T: 0.21
c [arjun] CMS::simplify() with *only* BVE...
c [arjun] CMS::simplify() with *only* BVE finished. T: 1.10
c [arjun] Adding fixed clauses time: 0.10
c [arjun] Start unknown size: 40
c [arjun] backward round finished T: 0.21
c [arjun] get_indep_set finished T: 6.36
c [appmc] Sampling set size: 34
c [appmc] Sampling set: 1062 1065 1069 1075 1076 1079 1082 1083 1086 1087
1088 1092 1095 1096 1099 1100 11
03 1104 1105 1108 1115 1117 1121 1126 1128 4181 4182 4183 4184 4185 4186
4199 4200 4201 0
c [appmc] threshold set to 72 sparse: 0
c [appmc] Starting at hash count: 0
c [appmc] [    0.00 ] round:  0 hashes:      0
c [appmc] [    0.00 ] bounded_sol_count looking for   73 solutions --
hashes active: 0
c [appmc] repeat solutions:      0 checked:      0 out of:      0
c [appmc] [    1.94 ] round:  0 hashes:      1
c [appmc] [    1.94 ] bounded_sol_count looking for   73 solutions --
hashes active: 1
c [appmc] repeat solutions:     46 checked:     73 out of:     73
c [appmc] [    3.08 ] round:  0 hashes:      2
c [appmc] [    3.08 ] bounded_sol_count looking for   73 solutions --
hashes active: 2
c [appmc] repeat solutions:     38 checked:    100 out of:    100
c [appmc] [    4.46 ] round:  0 hashes:      4
c [appmc] [    4.46 ] bounded_sol_count looking for   73 solutions --
hashes active: 4
c [appmc] repeat solutions:     12 checked:    135 out of:    135
c [appmc] [    6.44 ] round:  0 hashes:      8
c [appmc] [    6.44 ] bounded_sol_count looking for   73 solutions --
hashes active: 8
c [appmc] repeat solutions:     10 checked:    196 out of:    196
c [appmc] [    8.71 ] round:  0 hashes:     16
c [appmc] [    8.71 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:      0 checked:    259 out of:    259
c [appmc] [   11.58 ] round:  0 hashes:     32
c [appmc] [   11.58 ] bounded_sol_count looking for   73 solutions --
hashes active: 32
c [appmc] repeat solutions:      0 checked:    332 out of:    332
c [appmc] [   12.10 ] round:  0 hashes:     24
c [appmc] [   12.10 ] bounded_sol_count looking for   73 solutions --
hashes active: 24
c [appmc] repeat solutions:      0 checked:    332 out of:    332
c [appmc] [   12.10 ] round:  0 hashes:     20
c [appmc] [   12.10 ] bounded_sol_count looking for   73 solutions --
hashes active: 20
c [appmc] repeat solutions:      2 checked:    332 out of:    332
c [appmc] [   12.25 ] round:  0 hashes:     18
c [appmc] [   12.25 ] bounded_sol_count looking for   73 solutions --
hashes active: 18
c [appmc] repeat solutions:     19 checked:    332 out of:    337
c [appmc] [   13.31 ] round:  0 hashes:     17
c [appmc] [   13.31 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:     51 checked:    332 out of:    353
c [appmc] simplifying
c [appmc] [   15.11 ] round:  1 hashes:     17
c [appmc] [   15.11 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   16.68 ] round:  1 hashes:     16
c [appmc] [   16.68 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     61 checked:     73 out of:    134
c [appmc] simplifying
c [appmc] [   17.50 ] round:  2 hashes:     17
c [appmc] [   17.50 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   19.49 ] round:  2 hashes:     16
c [appmc] [   19.49 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     72 checked:     73 out of:    145
c [appmc] simplifying
c [appmc] [   20.03 ] round:  3 hashes:     17
c [appmc] [   20.03 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   22.68 ] round:  3 hashes:     16
c [appmc] [   22.68 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     65 checked:     73 out of:    138
c [appmc] simplifying
c [appmc] [   23.67 ] round:  4 hashes:     17
c [appmc] [   23.67 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   25.23 ] round:  4 hashes:     16
c [appmc] [   25.23 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     59 checked:     73 out of:    132
c [appmc] simplifying
c [appmc] [   26.35 ] round:  5 hashes:     17
c [appmc] [   26.35 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   27.94 ] round:  5 hashes:     16
c [appmc] [   27.94 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     54 checked:     73 out of:    127
c [appmc] simplifying
c [appmc] [   28.95 ] round:  6 hashes:     17
c [appmc] [   28.95 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   30.83 ] round:  6 hashes:     16
c [appmc] [   30.83 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     51 checked:     73 out of:    124
c [appmc] simplifying
c [appmc] [   32.21 ] round:  7 hashes:     17
c [appmc] [   32.21 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   34.06 ] round:  7 hashes:     16
c [appmc] [   34.06 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     54 checked:     73 out of:    127
c [appmc] simplifying
c [appmc] [   35.25 ] round:  8 hashes:     17
c [appmc] [   35.25 ] bounded_sol_count looking for   73 solutions --
hashes active: 17
c [appmc] repeat solutions:      0 checked:     73 out of:     73
c [appmc] [   36.75 ] round:  8 hashes:     16
c [appmc] [   36.75 ] bounded_sol_count looking for   73 solutions --
hashes active: 16
c [appmc] repeat solutions:     50 checked:     73 out of:    123
c [appmc] ApproxMC T: 37.66 s
ret: (59, 17)

So maybe you are doing something wrong. Please check the file test.py and
use the package that way.

Cheers,

Mate

**Comment by yizza91** [comment]
With German-0.cnf, it works also for me. But German-4.cnf doesn't and I am using the latest version

**Comment by yizza91** [comment]
I think that this occurs only when I call several times approxmc, and then the memory gets stuck. I try to delete the instance of Counter class but it doesn't solve the problem.
