### ISSUE TITLE
Infinite loops

### ISSUE THREAD

**Issue by yashpote** [meelgroup/ApproxMC#5]
Hi,

I found an input for which ApproxMC seemingly goes into an infinite loop in the first iteration itself.
`approxmc   --threshold 3 --measure 1 test.txt` 
[test.txt](https://github.com/meelgroup/ApproxMC/files/2919616/test.txt)

It's the same for thresholds in {1,2,3}.

I tried with different seeds, {1,2,3,4,5}, and for each seed ApproxMC went into an infinite loop when threshold=1.

Thanks,
Yash

**Comment by msoos** [comment]
Wow, super nice catch! It was a conceptual error, too, so I liked this very much! I'll let Kuldeep Meel know. The issue was that we assumed that, in this case, adding 500 XORs with 500 sampling set size will give us at most 1 solution. We of course were wrong, the XORs sometimes don't cut half the way through. The maximum number of XORs had to be adjusted. It's now approximated to be:

```
sampling_size*1.2+5
```
Pretty dumb but should do the trick. The +5 is for smaller sampling sizes and the 1.2 is to make sure it works on larger sampling sizes. Should work OK, I think!

Thanks again, great catch :) Please re-open in case you find a file that has a similar issue, we'll investigate further then.

**Comment by yashpote** [comment]
I read on this link that the expected rank for a N x N matrix is about N-1, so I thought the count night be wrong at around N xors.  
 [https://math.stackexchange.com/questions/324150/expected-rank-of-a-random-binary-matrix](stackoverflow) 
This might be useful to decide where how much of a correction to make. I think the effect is only significant around N-10 rows and also not dependent on N.
